# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
