# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_quiz', '0003_round3_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round3_answer',
            name='input',
        ),
        migrations.AddField(
            model_name='round3_answer',
            name='user_input',
            field=models.CharField(default=1, max_length=200, verbose_name='Answer'),
            preserve_default=False,
        ),
    ]
